課題①-4完了
tamaji22/JavaScript_task1-4 pull request #1
Opened 2020-11-12 11:41 UTC by tamaji22

課題①-4が完了しました。
確認をお願い致します。

2020-11-14 03:09 UTC, niganium reviewed
お疲れ様です。何点かコメントしました。
修正したのち再提出をお願いいたします。

2020-11-14 03:09 UTC, niganium commented on index.html
> +      while (task !== null) {
タスク追加が完了してもループが走ります。修正しましょう

2020-11-14 03:09 UTC, niganium commented on index.html
> +        ["机を片付ける", "掃除"],
個別のタスクは
```
{content: "aae", genre: 'test'},
```

などの連想配列で管理した方がまとまりとして管理しやすいです。

2020-11-16 11:39 UTC, tamaji22 commented
お疲れさまです。
指摘された点を修正しました。

1. タスクの配列を連想配列に変更
2. タスクを追加したあともループが走るので、ループそのものを削除

以上です、確認をよろしくお願いいたします。

2020-11-17 12:46 UTC, myzktkyk requested changes
1点だけ指摘をしております。

2020-11-17 12:46 UTC, myzktkyk commented on index.html
> +        tasks.forEach(function (task, index) {
アロー関数を使うほうが今どきかなと思いました。
```suggestion
        tasks.forEach((task, index) => {
```

2020-11-17 13:01 UTC, tamaji22 commented
指摘された点を
無名関数からアロー関数へ変更しました。
確認をお願い致します。

2020-11-19 11:26 UTC, merged